---

- name: 'VNC server packages installed'
  loop: '{{ vncserver_packages }}'
  package:
    name: '{{ item }}'
    state: 'present'

- name: 'systemd service override directory created'
  file:
    path: '/etc/tigervnc'
    state: 'directory'

- name: 'vncserver.users exists'
  file:
    path: '/etc/tigervnc/vncserver.users'
    state: touch

- name: 'vncserver-config-defaults exists'
  file:
    path: '/etc/tigervnc/vncserver-config-defaults'
    state: touch

- name: 'vncserver.users populated'
  lineinfile:
    path: '/etc/tigervnc/vncserver.users'
    line: ':1={{ vnc_server_user }}'

- name: 'vncserver-config-defaults populated'
  blockinfile:
    path: '/etc/tigervnc/vncserver-config-defaults'
    block: |
      interface=172.17.0.1
      rfbauth=/home/{{ vnc_server_user }}/.vnc/passwd
      MaxCutText=99999999

- name: 'SELinux context restored for .vnc directory'
  command: 'restorecon -RFv /home/{{ vnc_server_user }}/.vnc'

- name: 'systemd service override directory created'
  file:
    path: '/etc/systemd/system/vncserver@.service.d'
    state: 'directory'

- name: 'systemd service start order override templated'
  template:
    src: 'start_order.conf.j2'
    dest: '/etc/systemd/system/vncserver@.service.d/start_order.conf'

- name: 'systemd unit file templated'
  template:
    src: 'centos-7-vncserver@.service.j2'
    dest: '/etc/systemd/system/vncserver@.service'

- name: 'systemd service for gdm restarted'
  systemd:
    name: 'gdm.service'
    daemon_reload: 'yes'
    enabled: 'yes'
    state: 'restarted'

- name: 'systemd service enabled and started'
  systemd:
    name: 'vncserver@1.service'
    daemon_reload: 'yes'
    enabled: 'yes'
    state: 'started'
