---

version: '3.2'
networks:
  exo-guac-net:
    driver: bridge
services:
  exo-watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_LABEL_ENABLE: 'true'
  exo-guac-guacd:
    image: 'guacamole/guacd:latest'
    restart: 'always'
    hostname: 'guacd'
    networks:
      exo-guac-net:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  exo-guac-guacamole:
    image: 'guacamole/guacamole:latest'
    restart: 'always'
    networks:
      exo-guac-net:
    depends_on:
      - 'exo-guac-guacd'
    links:
      - 'exo-guac-guacd:guacd'
    environment:
      GUACD_HOSTNAME: 'guacd'
      GUACAMOLE_HOME: '/config'
    volumes:
      - type: 'bind'
        source: './config'
        target: '/config'
    ports:
      - '49528:8080'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"